#!/bin/bash

BASE=$HOME/project/mkprefix
PREFIXTEMP1=$(mktemp)
PREFIXTEMP2=$(mktemp)

if [ ! -d $BASE ] ; then
    mkdir -p $BASE
fi

if [ -f $BASE/$1.conf ] || [ -f $BASE/$1.cmds ] ; then
    . $BASE/$1.conf
    else
    echo "cannot find $BASE/$1.cmds or $BASE/$1.conf"
    exit 2
fi


/usr/bin/ssh -t -t -p $PORT -l $USER $HOST < $1.cmds \
    | grep "*>" \
    | awk {'print$2'} \
    | grep -Ev '.0\"$|/25|/26|/27|/28|/29|/30|/32' \
    > $PREFIXTEMP1

cat > $PREFIXTEMP2 << EOF
# Script untuk menambahkan IP Address BGP yang terdaftar di SIX
# ke RouterOS dalam ADDRESS-LIST dengan nama "nice"
# Created by Mahyuddin Susanto <udienz@rad.net.id>
# Inspired by http://ixp.mikrotik.co.id/download/nice.rsc
# Last generate $(date -R)

/sys note set show-at-login=yes note="Using six.rsc from rad.net.id, $(date -R)"
/ip firewall address-list
add list=six address="1.2.3.4"
rem [find list="six"]
EOF

cat $PREFIXTEMP1 | while read ip
    do
    # add list=nice address="120.160.0.0/11"
    echo "add list six address=\"$ip\"" >> $PREFIXTEMP2
    done

sed -i 's/.0$/.0\/24/g' $PREFIXTEMP2

cp $PREFIXTEMP2 $BASE/six.rsc

rm -f $PREFIXTEMP1 $PREFIXTEMP2
