#!/bin/bash
set -x
BASE=$HOME/git/mkprefix
PREFIXTEMP1=$(mktemp)
PREFIXTEMP2=$(mktemp)
NAME=$1

if [ ! -d $BASE ] ; then
    mkdir -p $BASE
fi

cd $BASE

if [ -f $BASE/$1.conf ] || [ -f $BASE/$1.cmds ] ; then
    . $BASE/$1.conf
    else
    echo "cannot find $BASE/$NAME.cmds or $BASE/$NAME.conf"
    exit 2
fi


/usr/bin/ssh -t -t -p $PORT -l $USER $HOST < $1.cmds \
    | grep "*>" \
    | sed -e 's/i/ /g' \
    | awk {'print$2'} \
    | sed -e 's/i/ /g'  \
    | sed -e 's/\.0$/\.0\/24/g' \
    > $PREFIXTEMP1
cat > $PREFIXTEMP2 << EOF
# Script untuk menambahkan IP Address BGP yang terdaftar di $NAME
# ke RouterOS dalam ADDRESS-LIST dengan nama "nice"
# Created by Mahyuddin Susanto <udienz@rad.net.id>
# Inspired by http://ixp.mikrotik.co.id/download/nice.rsc
# Last generate $(date -R)

/sys note set show-at-login=yes note="Using six.rsc from rad.net.id, $(date -R)"
/ip firewall address-list
add list=$NAME address="1.2.3.4"
rem [find list="$NAME"]
EOF

cat $PREFIXTEMP1 | while read ip
    do
    # add list=nice address="120.160.0.0/11"
    echo "add list=$NAME address=\"$ip\"" >> $PREFIXTEMP2
    done

# Remove prefix lower than /24

grep -Ev '/20|/21|/22|/25|/26|/27|/28|/29|/30|/32' $PREFIXTEMP2 > $BASE/$NAME.rsc
grep -Ev '/20|/25|/26|/27|/28|/29|/30|/32' $PREFIXTEMP2 > $BASE/$NAME.rsc
chmod +r $BASE/$NAME.rsc
mv $BASE/$NAME.rsc $BASE/out/$NAME.rsc
cp $PREFIXTEMP1 $BASE/out/$NAME.dump
chmod 755 $BASE/out/ -R
rm -f $PREFIXTEMP1 $PREFIXTEMP2